### ISSUE TITLE
Problem: Train on my own dataset.

### ISSUE THREAD

**Issue by surserrr** [TuSimple/simpledet#227]
Thanks for your excellent work！
I want to train my own dataset using tridentnet. I convert my dataset to coco and run create_coco_roidb.py , change gpus and num_class in config. Do I need to change another parameters? 

And I meet the problem when run  
python detection_train.py --config config/tridentnet_r101v1c4_c5_1x.py 

Traceback (most recent call last):
  File "detection_train.py", line 290, in <module>
    train_net(parse_args())
  File "detection_train.py", line 21, in train_net
    transform, data_name, label_name, metric_list = config.get_config(is_train=True)
  File "/media/fangjt/3dc196fc-1311-49bb-ad24-5f77d8735211/simpledet/config/tridentnet_r101v1c4_c5_1x.py", line 132, in get_config
    num_branch=Trident.num_branch, scaleaware=Trident.train_scaleaware)
  File "/media/fangjt/3dc196fc-1311-49bb-ad24-5f77d8735211/simpledet/models/tridentnet/builder.py", line 84, in get_train_symbol
    rpn_loss = rpn_head.get_loss(rpn_feat, rpn_cls_label, rpn_reg_target, rpn_reg_weight)
  File "/media/fangjt/3dc196fc-1311-49bb-ad24-5f77d8735211/simpledet/models/tridentnet/builder.py", line 310, in get_loss
    image_anchor = p.anchor_assign.image_anchor
AttributeError: 'NoneType' object has no attribute 'image_anchor'

**Comment by RogerChern** [comment]
Sorry, this is a regression introduced by #224. Please change `anchor_assign` to `anchor_generate`

**Comment by RogerChern** [comment]
Close by #228
